<div style="text-align: center;">
    <img src="https://media.licdn.com/dms/image/v2/D4E0BAQE4bCQaEBYDUQ/company-logo_200_200/company-logo_200_200/0/1728590235264/hobotacademy_logo?e=1738195200&v=beta&t=0DiMS1wnJYE6nkBjL237Lh3mTm8GKEy_s65hG_yiTSs" alt="Hobot Academy Logo" width="200"/>
</div>

<h1 style="text-align: center;">Math</h1>
<h2 style="text-align: center;">Session04</h2>
<h3 style="text-align: center;">Span</h3>
<h3 style="text-align: center;">Zahra Amini</h3>

<div style="width: 100%; text-align: center;">
    <table style="margin: 0 auto;">
        <tr>
            <td>
                <a href="https://t.me/hobotacademy">Telegram</a><br>
                <a href="https://www.linkedin.com/company/hobotacademy">LinkedIn</a><br>
                <a href="https://www.youtube.com/@AcademyHobot">YouTube</a><br>
            </td>
            <td>
                <a href="https://github.com/hobotacademy">GitHub</a><br>
                <a href="https://www.kaggle.com/aminizahra">Kaggle</a><br>
                <a href="https://www.instagram.com/hobot.academy/">Instagram</a><br>
            </td>
        </t>
    </table>
</div>
>
    </table>
</div>
>
    </table>
</div>

## Section 1

In [1]:
import numpy as np

In [2]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])

In [3]:
v1 + v2

array([4, 6])

In [4]:
3 * v1

array([3, 6])

In [5]:
def is_in_subspace(v, subspace_vectores):
    A = np.column_stack(subspace_vectores)
    try:
        coeffs = np.linalg.lstsq(A, v, rcond=None)[0]
        return np.allclose(np.dot(A, coeffs), v)
    except np.linalg.LinAlgError:
        return False

In [6]:
v = np.array([5, 7])
subspace = [np.array([1, 0]), np.array([0, 1])]
is_in_subspace(v, subspace)

True

## Section 2

In [7]:
def linear_comb(vectors, scalars):
    result = np.zeros_like(vectors[0])
    for v, s in zip(vectors, scalars):
        result += s * v
    return result

In [8]:
v1, v2

(array([1, 2]), array([3, 4]))

In [9]:
scalars = [2, -1]

In [10]:
linear_comb([v1, v2], scalars)

array([-1,  0])

## Section 3

In [11]:
def are_linearly_independent(vectors):
    A = np.column_stack(vectors)
    return np.linalg.matrix_rank(A) == len(vectors)

In [12]:
v1 = np.array([1, 2])
v2 = np.array([2, 4])
v3 = np.array([3, 1])

In [13]:
are_linearly_independent([v1, v2])

np.False_

In [14]:
are_linearly_independent([v1, v3])

np.True_

## Section 4