<div style="text-align: center;">
    <img src="https://media.licdn.com/dms/image/v2/D4E0BAQE4bCQaEBYDUQ/company-logo_200_200/company-logo_200_200/0/1728590235264/hobotacademy_logo?e=1738195200&v=beta&t=0DiMS1wnJYE6nkBjL237Lh3mTm8GKEy_s65hG_yiTSs" alt="Hobot Academy Logo" width="200"/>
</div>

<h1 style="text-align: center;">Math</h1>
<h2 style="text-align: center;">Session04</h2>
<h3 style="text-align: center;">Matrix Decomposition</h3>
<h3 style="text-align: center;">Zahra Amini</h3>

<div style="width: 100%; text-align: center;">
    <table style="margin: 0 auto;">
        <tr>
            <td>
                <a href="https://t.me/hobotacademy">Telegram</a><br>
                <a href="https://www.linkedin.com/company/hobotacademy">LinkedIn</a><br>
                <a href="https://www.youtube.com/@AcademyHobot">YouTube</a><br>
            </td>
            <td>
                <a href="https://github.com/hobotacademy">GitHub</a><br>
                <a href="https://www.kaggle.com/aminizahra">Kaggle</a><br>
                <a href="https://www.instagram.com/hobot.academy/">Instagram</a><br>
            </td>
        </t>
    </table>
</div>
>
    </table>
</div>
>
    </table>
</div>

# Import

In [3]:
import numpy as np
from scipy.linalg import lu
from scipy.linalg import lu_factor, lu_solve

# LU Decomposition

In [2]:
A = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])
b = np.array([5, -2, 9])

In [4]:
lu, piv = lu_factor(A)

In [7]:
lu

array([[ 4. , -6. ,  0. ],
       [ 0.5,  4. ,  1. ],
       [-0.5,  1. ,  1. ]])

In [8]:
piv

array([1, 1, 2], dtype=int32)

In [5]:
x = lu_solve((lu, piv), b)

In [6]:
x

array([1., 1., 2.])

# QR Decomposition

# Eigenvalue and Eigenvector Decomposition

In [9]:
A = np.array([[4, 1], [2, 3]]) # a11, a22

In [10]:
# det(A - lambda I) = 0 -> +1 * lambda^2 - trace(A)lambda + det(A) = 0
# trace(A) = Sum of diagnal elements

In [11]:
trace_A = np.trace(A)
trace_A

np.int64(7)

In [12]:
det_A = np.linalg.det(A)
det_A

np.float64(10.000000000000002)

In [13]:
# a x^2 + b x + c, x (-b +/- sqrt(b62 - 4ac) )/ 2a
# lambda = -b +/- sqrt(b^2 - 4ac)]/2a
# a=1, b = -trace(A), c = det(A)

In [14]:
b = -trace_A
c = det_A

In [15]:
eigenvalue1 = (-b + np.sqrt(b**2 - 4 * 1 * c)) / (2 * 1)
eigenvalue2 = (-b - np.sqrt(b**2 - 4 * 1 * c)) / (2 * 1)

In [16]:
eigenvalue1, eigenvalue2

(np.float64(4.999999999999999), np.float64(2.000000000000001))

In [17]:
# (A - lambda I) = 0

lambda_1 = eigenvalue1
I = np.eye(2)
A_lambda_1 = A - lambda_1 * I
A_lambda_1

array([[-1.,  1.],
       [ 2., -2.]])

In [18]:
_, _, v1 = np.linalg.svd(A_lambda_1)
v1

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [19]:
np.linalg.eig(A)

EigResult(eigenvalues=array([5., 2.]), eigenvectors=array([[ 0.70710678, -0.4472136 ],
       [ 0.70710678,  0.89442719]]))