<div style="text-align: center;">
    <img src="https://media.licdn.com/dms/image/v2/D4E0BAQE4bCQaEBYDUQ/company-logo_200_200/company-logo_200_200/0/1728590235264/hobotacademy_logo?e=1738195200&v=beta&t=0DiMS1wnJYE6nkBjL237Lh3mTm8GKEy_s65hG_yiTSs" alt="Hobot Academy Logo" width="200"/>
</div>

<h1 style="text-align: center;">Math</h1>
<h2 style="text-align: center;">Session02</h2>
<h3 style="text-align: center;">Matrices Multiply</h3>
<h3 style="text-align: center;">Zahra Amini</h3>

<div style="width: 100%; text-align: center;">
    <table style="margin: 0 auto;">
        <tr>
            <td>
                <a href="https://t.me/hobotacademy">Telegram</a><br>
                <a href="https://www.linkedin.com/company/hobotacademy">LinkedIn</a><br>
                <a href="https://www.youtube.com/@AcademyHobot">YouTube</a><br>
            </td>
            <td>
                <a href="https://github.com/hobotacademy">GitHub</a><br>
                <a href="https://www.kaggle.com/aminizahra">Kaggle</a><br>
                <a href="https://www.instagram.com/hobot.academy/">Instagram</a><br>
            </td>
        </t>
    </table>
</div>
>
    </table>
</div>
>
    </table>
</div>

In [3]:
import numpy as np

## Matrix Multiplication

In [4]:
def matrix_multiply(A, B):

    # Check if multiplication is possible
    if len(A[0]) != len(B):
        raise ValueError("Number of columns in A must equal number of rows in B")
    
    # Initialize the resulting matrix with zeros
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    
    # Compute matrix multiplication
    for i in range(len(A)):  # Loop over rows of A
        for j in range(len(B[0])):  # Loop over columns of B
            for k in range(len(B)):  # Loop over common dimension
                result[i][j] += A[i][k] * B[k][j]
    
    return result

# Example Matrices
A = [
    [1, 2, 3],
    [4, 5, 6]
]

B = [
    [7, 8],
    [9, 10],
    [11, 12]
]

# Perform Matrix Multiplication
result = matrix_multiply(A, B)

# Display Result
print("Matrix A:")
for row in A:
    print(row)

print("\nMatrix B:")
for row in B:
    print(row)

print("\nResulting Matrix C:")
for row in result:
    print(row)

Matrix A:
[1, 2, 3]
[4, 5, 6]

Matrix B:
[7, 8]
[9, 10]
[11, 12]

Resulting Matrix C:
[58, 64]
[139, 154]


In [5]:
# Example Matrices
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# Perform Matrix Multiplication
C = np.dot(A, B)

# Display Results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nResulting Matrix C:")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Resulting Matrix C:
[[ 58  64]
 [139 154]]


## Hadamard Product

In [6]:
# Example Matrices
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

# Perform Hadamard Product
C = np.multiply(A, B)  # Element-wise multiplication
# Alternatively, you can use `C = A * B` for the same result

# Display Results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nHadamard Product (Element-wise multiplication):")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Hadamard Product (Element-wise multiplication):
[[ 7 16 27]
 [40 55 72]]


## Outer Product

In [7]:
# Example vectors
u = np.array([1, 2, 3])  # Vector of size 3
v = np.array([4, 5])     # Vector of size 2

# Perform Outer Product
result = np.outer(u, v)

# Display Results
print("Vector u:", u)
print("Vector v:", v)
print("\nOuter Product (NumPy Implementation):")
print(result)

Vector u: [1 2 3]
Vector v: [4 5]

Outer Product (NumPy Implementation):
[[ 4  5]
 [ 8 10]
 [12 15]]


## Inner Product

In [8]:
# Example Vectors
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Compute Inner Product
result = np.dot(u, v)

# Display Result
print(f"Vector u: {u}")
print(f"Vector v: {v}")
print(f"Inner Product: {result}")


Vector u: [1 2 3]
Vector v: [4 5 6]
Inner Product: 32


## Dot Product

In [9]:
# Example Vectors
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Compute Dot Product
dot_product = np.dot(u, v)

print("Vector u:", u)
print("Vector v:", v)
print("Dot Product:", dot_product)

Vector u: [1 2 3]
Vector v: [4 5 6]
Dot Product: 32


## Kronecker Product

In [10]:
# Define Matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[0, 5],
              [6, 7]])

# Compute Kronecker Product
kronecker_product = np.kron(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nKronecker Product (A ⊗ B):")
print(kronecker_product)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[0 5]
 [6 7]]

Kronecker Product (A ⊗ B):
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


## Cross Product

In [11]:
u = np.array([2, 3, 4])
v = np.array([5, 6, 7])
result = np.cross(u, v)
print("Cross Product:", result)

Cross Product: [-3  6 -3]
