<div style="text-align: center;">
    <img src="https://media.licdn.com/dms/image/v2/D4E0BAQE4bCQaEBYDUQ/company-logo_200_200/company-logo_200_200/0/1728590235264/hobotacademy_logo?e=1738195200&v=beta&t=0DiMS1wnJYE6nkBjL237Lh3mTm8GKEy_s65hG_yiTSs" alt="Hobot Academy Logo" width="200"/>
</div>

<h1 style="text-align: center;">Math</h1>
<h2 style="text-align: center;">Session01</h2>
<h3 style="text-align: center;">Introduction to Matrices and Vectors</h3>
<h3 style="text-align: center;">Zahra Amini</h3>

<div style="width: 100%; text-align: center;">
    <table style="margin: 0 auto;">
        <tr>
            <td>
                <a href="https://t.me/hobotacademy">Telegram</a><br>
                <a href="https://www.linkedin.com/company/hobotacademy">LinkedIn</a><br>
                <a href="https://www.youtube.com/@AcademyHobot">YouTube</a><br>
            </td>
            <td>
                <a href="https://github.com/hobotacademy">GitHub</a><br>
                <a href="https://www.kaggle.com/aminizahra">Kaggle</a><br>
                <a href="https://www.instagram.com/hobot.academy/">Instagram</a><br>
            </td>
        </t>
    </table>
</div>
>
    </table>
</div>
>
    </table>
</div>

# Libraries

In [1]:
import numpy as np

# Section01

## 1.1 Definition of a Vector and Notation

In [2]:
v = np.array([0.2, -0.7, 0.5, 1.2])

In [3]:
v

array([ 0.2, -0.7,  0.5,  1.2])

In [4]:
v.shape

(4,)

In [5]:
v.reshape(4,1)

array([[ 0.2],
       [-0.7],
       [ 0.5],
       [ 1.2]])

## 1.2 Unit Vectors

In [6]:
def unit_vector(v):
    norm = np.linalg.norm(v)
    return v/norm

In [7]:
v = np.array([3, -4, 5])
u = unit_vector(v)
print("Unit Vector is ", u)

Unit Vector is  [ 0.42426407 -0.56568542  0.70710678]


## 1.3 Addition and Subtraction of Vectors

In [9]:
a = np.array([2, 3, 1])
b = np.array([5, -1, 4])

add = a + b

sub = a - b

print(add, sub)

[7 2 5] [-3  4 -3]


## 1.4 Scalar Multiplication

In [10]:
v = np.array([1.5, -3, 4])
scalar = 2.5

scalar * v

array([ 3.75, -7.5 , 10.  ])

## 1.5 Norm of a Vector

In [11]:
v = np.array([1, -2, 2, -3])

In [12]:
np.linalg.norm(v)

np.float64(4.242640687119285)

## 1.6 Dot Product

In [13]:
a = np.array([2, 3, -1])
b = np.array([4, -1, 5])

In [14]:
np.dot(a, b)

np.int64(0)

## 1.7 Angle Between Two Vectors and Its Applications in Machine Learning

In [15]:
def cosin_sim(a, b):
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_product / (norm_a * norm_b)

In [16]:
a = np.array([3, -5])
b = np.array([7, 1])

In [18]:
cos_theta = cosin_sim(a, b)

In [20]:
np.degrees(np.arccos(cos_theta))

np.float64(67.16634582208245)

# Section02

## 2.1 Identity Matrix

In [21]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.dot(A, I)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [25]:
np.dot(A, I) == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 2.2 Non-Zero Matrix

In [26]:
A = np.array([[0, 2, 0], [1, 0, 3], [0, 0, 4]])
A

array([[0, 2, 0],
       [1, 0, 3],
       [0, 0, 4]])

## 2.3 Sparse Matrix

In [27]:
from scipy.sparse import csr_matrix

In [28]:
s = csr_matrix([[0, 0, 3], [0, 0, 0], [0, 0, 0]])

In [30]:
s

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1 stored elements and shape (3, 3)>

In [31]:
s.toarray()

array([[0, 0, 3],
       [0, 0, 0],
       [0, 0, 0]])

## 2.4,5,6 Singular & Non-singular Matrix & Inverse 

## 2.7 Diagonal Matrix

## 2.2 Symmetric Matrix

# Section03

## 3.1 Calculate Matrix Rank